export {default as Home} from './Home/Home'
export {default as About} from './About/About'
export {default as Project} from './Projects/Project'
export {default as Contact} from './Contact/Contact'
export {default as Tech} from './Tech/Tech'
export {default as Footer} from './Footer/Footer'