import CSS from "../assets/css.png";
import Firebase from "../assets/firebase.png";
import GITHUB from "../assets/github.png";
import HTML from "../assets/html.png";
import JAVASCRIPT from "../assets/javascript.png";
import MONGO from "../assets/mongo.png";
import NODE from "../assets/node.png";
import REACT from "../assets/react.png";
import Tailwind from "../assets/tailwind.png";
